import { extendTheme } from "@chakra-ui/react"
import { ButtonStyles as Button } from "../styles/components/buttonStyles"
import { CardStyles as Card } from "../styles/components/cardStyles"

export const customTheme = extendTheme({
    colors: {
        primary: "#8837B1",
        primaryLight: "#cf97e7",
        primaryDark: "#43145a",
        secondary: "#FFCE22",
        secondaryLight: "#FFE197",
        secondaryDark: "#816c1d",
        terciary: "#2ACED2",
        terciaryLight: "#85ebec",
        terciaryDark: "#16A2A7",
    },
    fonts: {
        body: `'Open Sans', sans-serif`,
        // heading: "Roboto Mono",
        heading: `'Open Sans', sans-serif`,
    },
    // space: {
    //     px: "1px",
    //     0.5: "0.125rem",
    //     1: "0.25rem",
    //     1.5: "0.375rem",
    //     2: "0.5rem",
    //     2.5: "0.625rem",
    //     3: "0.75rem",
    //     3.5: "0.875rem",
    //     4: "1rem",
    //     5: "1.25rem",
    //     6: "1.5rem",
    //     7: "1.75rem",
    //     8: "2rem",
    //     9: "2.25rem",
    //     10: "2.5rem",
    //     12: "3rem",
    //     14: "3.5rem",
    //     16: "4rem",
    //     20: "5rem",
    //     24: "6rem",
    //     28: "7rem",
    //     32: "8rem",
    //     36: "9rem",
    //     40: "10rem",
    //     44: "11rem",
    //     48: "12rem",
    //     52: "13rem",
    //     56: "14rem",
    //     60: "15rem",
    //     64: "16rem",
    //     72: "18rem",
    //     80: "20rem",
    //     96: "24rem",
    // },
    components: {
        Button,
        Card,
        Text: {
            baseStyle: {
                fontFamily: `'Open Sans', sans-serif`,
                fontWeight: "normal",
                lineHeight: "tall",
                color: "inherit",
            },
        },
    },
})
